# Config for music downloader

# ===============
# General options
# ===============

# if false, then music downloader will automatically try to fix invalid config options,
# such as creating missing directories, fixing bad numbers or using default values for missing options
strict-mode: false

# ==================
# Downloader options
# ==================

# Output directory where music will be placed
output-dir: "/home/bassam/music/"

# Input directory which contains files with the URLs to music
input-dir:  "./urls/"

# Audio formats to use, allowed formats are: m4a, mp3, flac, wav
formats:  [ "m4a" ]

# Cookies for each download source, empty string for no cookies file
cookies: "./cookies/youtube-cookies.txt"

# Archives directory to keep track of downloaded music, a directory will be made for each format
archives-dir: "./archives/"

# Download rate limit in MB/s, 0 for no limit
rate-limit: 0

# Period between rescan to check for new music in minutes
rescan-period: 360

# ytdl executable, this should be recognizable and runnable from a shell
executable: "yt-dlp"

# Is file enabled, if true will use a file watcher to check for changes to input-dir
file-watching-enabled: true

# ===============
# Storage options
# ===============

# Backup location(s)
backup-dirs:
  - "~/backups/"

# Backup period in minutes
backup-period: 720

