# Config for music downloader

# ===============
# General options
# ===============

# if false, then music downloader will automatically try to fix invalid config options,
# such as creating missing directories, fixing bad numbers or using default values for missing options
# if true, then if any config option is invalid, music download will not proceed
strict-mode: false

# ==================
# Downloader options
# ==================

# Output directory where music will be placed
output-dir: "~/data/music-manager/music/"

# Input directory which contains files with the URLs to music
input-dir:  "~/data/music-manager/input/"

# Audio formats to use, allowed formats are: m4a, mp3, flac, wav
formats:  [ "m4a" ]

# Cookies text file to download using authentication
cookies: "~/data/music-manager/youtube-cookies.txt"

# Archives directory to keep track of downloaded music
archives-dir: "~/data/music-manager/archives/"

# Download rate limit in MB/s, 0 for no limit
rate-limit: 0

# Period between rescan to check for new music in minutes
rescan-period: 360

# ytdl executable, this should be recognizable and runnable from a shell
executable: "./bin/yt-dlp"

# Seconds to sleep between downloads
sleep-seconds: 0

# Additional args to pass to the downloader executable for more fine tune control
downloader-args: ""

# ===========
# Log options
# ===========

# "Log verbosity, possible values are (case insensitive) :
#  NONE (N, Q), ERROR (E), WARN (W), DEBUG (D), INFO (I), VERBOSE (V)
log-level: INFO

# Directory where log files will be placed
log-dir: "~/music-manager/log/"

# ===============
# Storage options
# ===============

# Backup enabled
backup-enabled: true

# Backup location(s)
backup-dirs:
  - "~/music-manager/backups/"

# Backup period in minutes
backup-period: 720

