#!/usr/bin/env bash

run() {
  echo "Starting, first run may take some time"
  if [[ -z "$*" ]]; then
    ./gradlew build 1>/dev/null && java -classpath "$(./gradlew classpath)" dev.basshelal.musicdownloader.MainKt
  else
    ./gradlew build 1>/dev/null && java -classpath "$(./gradlew classpath)" dev.basshelal.musicdownloader.MainKt "$@"
  fi
}

checkUpdate() {
  if [[ $? -eq 69 ]]; then
    git fetch
    git pull
  fi
}

while true; do
run "$*"
checkUpdate
done
