#!/usr/bin/env bash

if [[ -z "$*" ]]; then
  ./gradlew music-downloader
else
  ./gradlew music-downloader --args="$*"
fi

# To run without Gradle
# java -classpath "$(./gradlew classpath)" dev.basshelal.musicdownloader.MainKt